== Co-Simulation Specific Issues

=== Early Return

Starting with FMI 3.0, co-simulation FMUs can optionally support early return from `fmi3DoStep` calls to allow more timely handling of internal events.

This capability can be used stand-alone, or in combination with <<Event-Handling in Co-Simulation,Event-Handling in Co-Simulation>>, as described below.

An FMU indicates its early return capability through the `mightReturnEarlyFromDoStep` and `canReturnEarlyAfterIntermediateUpdate` capability flags in its `modelDescription.xml` file.
Here `mightReturnEarlyFromDoStep` indicates the FMUs capability to return early on its own volition, whereas `canReturnEarlyAfterIntermediateUpdate` additionally indicates the FMUs capability to be forced by the importer to return early during intermediate update callbacks.

An importer indicates that it wants to use this capability by passing in `fmi3True` for the `earlyReturnAllowed` argument in the call to `fmi3InstantiateCoSimulation`.

An FMU can then return early from a call to `fmi3DoStep`, i.e. prior to fully completing its step to the full communication step, by setting the `earlyReturn` argument to `fmi3True`, and `lastSuccesfulTime` to the exact time the FMU computed up to, prior to returning from `fmi3DoStep`.

This allows an FMU to e.g. signal an internal event has occurred that the importer should take note of.

Note that if the FMU is used without external event handling enabled, any events will still be handled completely internally, and the early return is just used to give the importer a chance to take note of the event.
If early return capability is used in conjunction with external event handling, as described in <<Event-Handling in Co-Simulation>> below, then events are not only signalled but also need to be handled by the importer if so indicated by the FMU.

=== Event-Handling in Co-Simulation

Starting with FMI 3.0, co-simulation FMUs can optionally support external event-handling, i.e. notifying the co-simulation algorithm of the importer about events, which the importer then handles by putting the FMU into event mode, where event iteration can take place.
This is similar to the way model exchange has always supported external event handling.

An FMU indicates this capability through the `hasEventMode` capability flag in its `modelDescription.xml` file.
An importer indicates that it wants to use this capability by passing in `fmi3True` for the `eventModeUsed` argument in the call to `fmi3InstantiateCoSimulation`.

The FMU then indicates that event handling is needed by setting the `eventHandlingNeeded` argument to `fmi3True` in the call to `fmi3DoStep` prior to returning.

Note that this can interact with <<Early Return,Early Return>> in the following way:
If an FMU supports early return, and the importer has signaled support for early return (through `earlyReturnAllowed`), then if an event occurs prior to the end of the communication step, the FMU would return early with both `earlyReturn` and `eventHandlingNeeded` arguments set to `fmi3True`, and `lastSuccesfulTime` giving the exact time of the event.

If however an FMU either does not support early return, or is instantiated with `earlyReturnAllowed` set to `fmi3False`, then even if an event occurs prior to the end of the communication step, the FMU must continue to the end of the communication step.
It will indicate the event as usual through `eventHandlingNeeded` being set to `fmi3True`, and will have to expect the importer to enter event mode as usual.
However the exact point in time when the event occured will have already passed, and is not available to the importer.
This might require at least mitigative internal event handling by the FMU itself.

For this reason it is usually recommended to use event handling support and early return capabilities together, both for exporters and importers, as this will give the best event handling control.

=== Clock Tick Definitions and Clock Activations

Remember that a clock activation means setting its activation status to `fmi3ClockActive`, and that the source of a clock activation is

* for input clocks the importer, by calling fmi3setClock() on the clock's FMU.
* for output clocks the clock's FMU in Event Mode.

A clock tick is the (future) time instant of a clock activation, and its cause. The importer needs to keep track of clock ticks and if necessary, doStep the clock's FMU to the time instant of the clock tick.

The source of a clock tick's definition is

* for time-based input clocks and for triggered output clocks always the clock's FMU. The time instant of the clock tick is reported to the importer by clock-specific means.
* for triggered input clocks not constrained by the standard, and as such one or more of
** a triggered output clock activation of any FMU at the time instant of the tick.
** a tick of any time-based input clock of any FMU.
** any other source that the importer has knowledge of.
		
If the tick of a time-based input clock as cause of a triggered input clock's activation seems counter-intuitive, it may help to remember that

* inports and outports are always between importer and FMU, not FMU and FMU (the latter may only appear to be so to a user in the context of defining connections between outports and inports, e.g. in a typical GUI).
* the definition of a time-based clock's tick by an FMU is separate from the activation of that clock by the importer.
* the time-based input clock is not 'connected' to the triggered input clock (in the sense of connecting one FMUs output port to another FMUs input port), it is the importer that keeps track of the shared tick, if necessary doSteps the FMU(s) to the time instant of the shared tick, and activates each input clock.