[#top-profiles]
== Feature Profiles

The initial set of use-case-based feature profiles includes a set of five feature profiles, which can be seen in the overview in table <<feature-matrix,Feature Overview>>.
They are described in detail in the following sections.

=== Basic CS Profile

This is a basic profile for Co-Simulation, that should be supported on any binary target - especially for desktop simulation usage. There are no additional specific advanced Co-simulation specific requirements and typically fixed communication step sizes are used. 

Required Features::
  - Fixed-size Input/Output Arrays
  - Fixed-size Parameter Arrays

Recommended Features::
  - Tunable Parameters
  - Source Code FMUs
  - Resizable Parameter Arrays


=== Sensor Profile

This is a basic sensor simulation profile, supporting complex input and output using, for example, OSI-encoded sensor data via binary variables and dynamic timing.
Also suitable for non-sensor simulations with those characteristics.

Required Features::
  - Tunable Parameters
  - Binary Data Type Input/Output
  - Binary Data Type Parameters
  - Variable Co-Simulation Communication Step Size (*CS only*)

Recommended Features::
  - Source Code FMUs


=== XiL Profile

This is a profile supporting advanced Software-/Hardware-/X-in-the-Loop simulation, allowing for more efficient integration of multi-ECU networks.

Required Features::
  - Tunable Parameters
  - Binary Data Type Input/Output
  - Binary Data Type Parameters
  - Fixed-size Input/Output Arrays
  - Fixed-size Parameter Arrays
  - Resizable Parameter Arrays
  - Co-Simulation with Clock Information  (*CS only*)


Recommended Features::
  - Source Code FMUs
  - Variable Co-Simulation Communication Step Size (*CS only*)
  - Store/Restore FMU State(*CS only*)
  - Scheduled Execution Interface (*SE only*)


=== ECU Profile (tbd)

(all required and recommended feautures form XiL Profile)

Required Features:: 
- support of certain layerd standards (LS-BUS)

Recommended Features:: 
- support of certain layerd standards (LS-XCP)

=== Dynamics Profile

This is a profile for high dynamics mechatronic simulation, including variable cycle times, model exchange for allowing efficient handling of tightly coupled sub-systems, and the use of advanced co-simulation and model-exchange approaches.

Required Features::
  - Tunable Parameters
  - Fixed-size Input/Output Arrays
  - Fixed-size Parameter Arrays
  - State and Output Dependencies
  - Directional Derivatives (*ME only*)

Recommended Features::
  - Binary Data Type Input/Output
  - Resizable Parameter Arrays
  - Resizable Parameter Arrays with Size-Dependencies
  - Variable Co-Simulation Communication Step Size  (*CS only*)
  - Restartable Early Return in Hybrid Co-Simulation (*CS only*)
  - Output Derivatives in Co-Simulation (*CS only*)
  - Intermediate Variable Access (*CS only*)
  - Directional Derivatives (*CS only*)
  - Store/Restore FMU State (*CS only*)

=== Dynamics Controller Profile

This is a profile for high dynamics mechatronic simulation that includes discrete controller implementations.
This profile extends the dynamics profile to include model exchange with clocks to allow for efficient handling of tightly coupled sub-systems with reliable support for coupling discrete controller time partitions across FMUs.

(all required and recommended feautures form Dynamics Profile)

Required Features::
  - Clocked Model-Exchange (*ME only*)
  - Variable Co-Simulation Communication Step Size (*CS only*)
  - Restartable Early Return in Hybrid Co-Simulation (*CS only*)
  - Intermediate Variable Access  (*CS only*)
  - Co-Simulation with Clock Information (*CS only*)

=== Optimization Profile

This is a profile that caters to different but overlapping optimization use cases:
-	Model-predictive control (with the model as an FMU)
-	Parameter identification of a model via optimization
-	Training of ML models (e.g. neural networks) (need for adjoint derivatives, for Backpropagation)

Required Features::
  - Tunable Parameters
  - Fixed-size Input/Output Arrays
  - Fixed-size Parameter Arrays
  - State and Output Dependencies
  - Directional Derivatives
  - Adjoint Derivatives
  - Store/Restore FMU State (*CS only*)
  - Serialize/Deserialize FMU State (*CS only*)
  - Variable Co-Simulation Communication Step Size (*CS only*)
  - Output Derivatives in Co-Simulation (*CS only*)
  - Intermediate Variable Access (*CS only*)

  Recommended Features::
  - Resizable Parameter Arrays


=== Feature Overview

In the table below, the placement of an `X` indicates a required feature, and a `*` indicates a recommended feature.

[[feature-matrix]]
[cols="1h,<3,7*^1"]
|========
|Area|Feature|Basic CS Profile|Sensor Profile|XiL Profile|ECU Profile|Dynamics Profile|Dynamics Controller Profile|Optimization Profile

2+|Parameter Handling|||||||
| |Tunable Parameters|X|X|X|X|X|X|X
2+|State Handling|||||||
| |Store/Restore FMU State||||*|*|*|X
| |Serialize/Deserialize FMU State|||||||X
2+|Data Types|||||||
| |Binary Data Type Input/Output||X|X|*|*||
| |Binary Data Type Parameters||X|X|X|||
2+|Array Input/Output Handling|||||||
| |Fixed-size Arrays|X||X|X|X|X|X
| |Resizable Arrays|||||||
| |Resizable Arrays with Size-Dependencies|||||||
2+|Array Parameter Handling|||||||
| |Fixed-size Arrays|X||X|X|X|X|X
| |Resizable Arrays|*|||X|X|*|*
| |Resizable Arrays with Size-Dependencies|||||||
2+|Calculation Model|||||||
| |Variable Co-Simulation Communication Step Size||X|*|*|X|X|X
| |State and Output Dependencies|||||X|X|X
| |Output Derivatives in Co-Simulation|||||*|*|X
| |Directional Derivatives|||||*|*|X
| |Adjoint Derivatives|||||||X
| |Restartable Early Return in Hybrid Co-Simulation|||||*|*|X
| |Intermediate Variable Access|||||*|*|X
| |Co-Simulation with Clock Information|||||X|X|X
| |Scheduled Execution Interface||||*|||
| |Clocked Model-Exchange||||||X|
2+|Execution Targets|||||||
| |Source Code FMUs|*|*|X|X|||
|========


The support for source code FMUs is not strictly necessary for the Basic CS and Sensor profiles but is highly recommended to support the portability of FMUs to new platforms.

More generally, support for source code FMUs and binary FMUs for desktop and non-desktop platforms is recommended wherever feasible to aid portability and interoperability.