== Feature Profiles

The initial set of use-case based feature profiles includes the following profiles, which can be seen in overview in table XXX:

=== Basic CS Profile

Basic profile for Co-Simulation, intended mainly for desktop simulation uses, which have no additional specific requirements and can perform well with fixed communication step sizes.

=== Sensor Profile

Basic sensor simulation profile, supporting complex input and output using e.g. OSI-encoded sensor data via binary variables and dynamic timing. Also suitable for non-sensor simulations with those characterstics.

=== Basic HiL & Sensor HiL Profile

Basic Profile supporting HiL use, including mechatronic and sensor simulation usage. This assumes fixed cycle times, where dynamic internal cycle times are managed inside the FMUs.

=== SIL ECU Profile

Profile supporting advanced SiL simulation of ECU and other clocked models, allowing for more efficient integration of multi-ECU networks.

=== Dynamics Profile

Profile for high dynamics mechatronic simulation, including variable  cycle times, model-exchange to allow for efficient handling of tightly coupled sub-systems, and the use of advanced co-simulation and model-exchange approaches.

=== Feature Overview

[cols="1*h,7*"]
|========
|Area|Feature|FMI Version|Basic CS Profile|Sensor Profile|Basic HiL & Sensor HiL Profile|SIL ECU Profile|Dynamics Profile

2+|Parameter Handling||||||
| |Tunable Parameters|2.0|1|1|1|1|1
2+|State Handling||||||
| |Store/Restore FMU State|2.0||||1|1
| |Serialize/Deserialize FMU State|2.0|||||1
2+|Data Types||||||
| |String Inputs/Outputs|2.0|||||1
| |Binary Data Type Input/Output|3.0||1|1|1|1
| |Binary Data Type Parameters|3.0||1|1|1|
| |New Integer Types|3.0|||1|1|1
2+|Array Input/Output Handling||||||
| |Fixed-size Arrays|3.0|1||1|1|1
| |Dynamically resizable Arrays|3.0|1|||1|1
| |Resizable Arrays with Size-Dependencies|3.0|||||1
2+|Array Parameter Handling||||||
| |Fixed-size Arrays|3.0|1||1|1|1
| |Dynamically resizable Arrays|3.0|1|||1|1
| |Resizable Arrays with Size-Dependencies|3.0|||||1
2+|Calculation Model||||||
| |Variable Co-Simulation Communication Step Size|1.0||1||1|1
| |State and Output Dependencies|2.0|||||1
| |Output Derivatives in Co-Simulation|2.0|||||1
| |Directional Derivatives|2.0|||||
| |Restartable Early Return in Hybrid Co-Simulation|3.0|||||1
| |Intermediate Output Values in Co-Simulation|3.0|||||1
| |Co-Simulation with Clock Information|3.0||||1|1
| |Time Partition Activation Co-Simulation|3.0|||1|1|
| |Clocked Model-Exchange|3.0|||||
2+|Execution Targets||||||
| |Source Code FMUs|1.0|*|*|1|1|
| |Binary FMUs for Desktop Platforms|1.0|1|1|1|1|1
| |Binary FMUs for non-Desktop Platforms (e.g. HiL)|1.0|||1|1|
2+|Execution Mode||||||
| |Asynchronous FMUs|2.0|||||
|======
